src/GestionBundle/Entity/Repository/Entity/segVial/documentacion/habilitaciones/HabilitacionRepository.php
<?php

namespace GestionBundle\Entity\Repository\Entity\segVial\documentacion\habilitaciones;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\TurismoNacional;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;


class HabilitacionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllHabilitacionesActivas()
    {
        $qb = $this->createQueryBuilder('s')
                    ->where('s.activo = TRUE');

        $query = $qb->getQuery();

        return $query->execute();
    }

}

src/GestionBundle/Entity/segVial/documentacion/habilitaciones/Charter.php
<?php

namespace GestionBundle\Entity\segVial\documentacion\habilitaciones;

use Doctrine\ORM\Mapping as ORM;
use GestionBundle\Entity\ventas\Ciudad;


/**
 * @ORM\Table(name="gest_docum_habilitaciones_nacional_ol_charter")
 * @ORM\Entity
 */

class Charter extends OfertaLibre
{
    public function __toString()
    {
        return 'Oferta Libre Charter - '.$this->getCodigoHabilitacion();
    }

    public  function getType()
    {
        return 11;
    }

    public function getTexto()
    {
        return "Oferta Libre (Charter)";
    }
    
    public function getCalculaPagoAutomaticamente()
    {
        return false;
    }

}

src/GestionBundle/Form/segVial/documentacion/habilitaciones/CharterType.php
<?php

namespace GestionBundle\Form\segVial\documentacion\habilitaciones;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\Charter;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use GestionBundle\Entity\segVial\documentacion\OrganismoEstatal;
use GestionBundle\Form\segVial\documentacion\VencimientoType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class CharterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('vto', VencimientoType::class, ['data_class' => Charter::class])
            ->add('codigoHabilitacion')
            ->add('proveedor', 
                  EntityType::class,
                  [
                    'class' => OrganismoEstatal::class
                  ])
            ->add('origen')
            ->add('destino')
            ->add('cantCuotas')
            ->addEventListener(FormEvents::PRE_SET_DATA, 
                  function (FormEvent $event) {
                                                $charter = $event->getData();
                                                $form = $event->getForm();

                                                if (!$charter->getId()) 
                                                {
                                                    $form->add('renuevaVencimiento', 
                                                                  EntityType::class,
                                                                  [
                                                                    'class' => Charter::class,
                                                                    'required' => false,
                                                                  ]);
                                                }
                                                else
                                                {
                                                    return;
                                                }
                                            })
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Charter::class,
        ]);
    }
}

src/GestionBundle/Form/segVial/documentacion/habilitaciones/ContratadoType.php
<?php

namespace GestionBundle\Form\segVial\documentacion\habilitaciones;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\Contratado;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use GestionBundle\Entity\segVial\documentacion\OrganismoEstatal;
use GestionBundle\Form\segVial\documentacion\VencimientoType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class ContratadoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('vto', VencimientoType::class, ['data_class' => Contratado::class])
            ->add('codigoHabilitacion')
            ->add('proveedor', 
                  EntityType::class,
                  [
                    'class' => OrganismoEstatal::class
                  ])
            ->add('origen')
            ->add('destino')
            ->add('cliente')
            ->add('cantCuotas')
            ->addEventListener(FormEvents::PRE_SET_DATA, 
                  function (FormEvent $event) {
                                                $contratado = $event->getData();
                                                $form = $event->getForm();

                                                if (!$contratado->getId()) 
                                                {
                                                    $form->add('renuevaVencimiento', 
                                                                  EntityType::class,
                                                                  [
                                                                    'class' => Contratado::class,
                                                                    'required' => false,
                                                                  ]);
                                                }
                                                else
                                                {
                                                    return;
                                                }
                                            })
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contratado::class,
        ]);
    }
}

src/GestionBundle/Form/segVial/documentacion/habilitaciones/TurismoNacionalType.php
<?php

namespace GestionBundle\Form\segVial\documentacion\habilitaciones;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\TurismoNacional;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use GestionBundle\Entity\segVial\documentacion\OrganismoEstatal;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use GestionBundle\Form\segVial\documentacion\Vencimiento;
use GestionBundle\Form\segVial\documentacion\VencimientoType;


class TurismoNacionalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('vto', VencimientoType::class, ['data_class' => TurismoNacional::class])
            ->add('proveedor',EntityType::class,
                  [
                    'class' => OrganismoEstatal::class
                  ])
            ->add('codigoHabilitacion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TurismoNacional::class,
        ]);
    }
}

src/GestionBundle/Controller/GestionDocumentosController.php
<?php

namespace GestionBundle\Controller;

use DH\Auditor\Provider\Doctrine\DoctrineProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use GestionBundle\Entity\segVial\documentacion\CompaniaSeguro;
use GestionBundle\Form\segVial\documentacion\SeguroType;
use GestionBundle\Entity\segVial\documentacion\Seguro;
use GestionBundle\Form\segVial\documentacion\VerificacionTecnicaNacionalType;
use GestionBundle\Entity\segVial\documentacion\VerificacionTecnicaNacional;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use GestionBundle\Form\segVial\documentacion\VerificacionTecnicaProvincialType;
use GestionBundle\Entity\segVial\documentacion\VerificacionTecnicaProvincial;
use GestionBundle\Entity\segVial\documentacion\VerificacionTecnica;
use GestionBundle\Entity\segVial\documentacion\finanzas\CuotaVencimiento;
use GestionBundle\Entity\segVial\documentacion\finanzas\CuotaUnidad;
use GestionBundle\Entity\segVial\documentacion\Vencimiento;
use GestionBundle\Form\segVial\documentacion\finanzas\CuotaVencimientoType;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\TurismoNacional;
use GestionBundle\Form\segVial\documentacion\habilitaciones\TurismoNacionalType;
use GestionBundle\Entity\segVial\documentacion\habilitaciones\OfertaLibre;
use GestionBundle\Entity\segVial\documentacion\habilitaciones\Habilitacion;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\Charter;
use GestionBundle\Form\segVial\documentacion\habilitaciones\CharterType;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\Contratado;
use GestionBundle\Form\segVial\documentacion\habilitaciones\ContratadoType;

use GestionBundle\Entity\segVial\documentacion\habilitaciones\TurismoProvincial;
use GestionBundle\Form\segVial\documentacion\habilitaciones\TurismoProvincialType;

use GestionBundle\Form\segVial\documentacion\CompaniaSeguroType;

use GestionBundle\Entity\segVial\documentacion\opciones\TipoDestinoSeguro;
use GestionBundle\Form\segVial\opciones\TipoDestinoSeguroType;
use GestionBundle\Entity\segVial\documentacion\opciones\CoberturaSeguro;
use GestionBundle\Form\segVial\opciones\CoberturaSeguroType;
use GestionBundle\Entity\segVial\documentacion\PlantaVerificacion;
use GestionBundle\Form\segVial\opciones\PlantaVerificacionType;
use GestionBundle\Entity\segVial\documentacion\OrganismoEstatal;
use GestionBundle\Form\segVial\opciones\OrganismoEmisorType;

/**
 * @Route("/documentos")
 */

class GestionDocumentosController extends AbstractController
{
    private $provider, $validator, $params;

    public function __construct(DoctrineProvider $dp, ValidatorInterface $validator, ParameterBagInterface $params)
    {
        $this->provider = $dp;
        $this->validator = $validator;
        $this->params = $params;
    }

    ////////////////UTILS///////////////////

    private function validateEntity($entity)
    {
        $validator = $this->validator;//get('validator');

        $groups = ['general'];


        $errors = $validator->validate($entity, null, $groups);

        $details = [];

        if (count($errors))
        {
            
            foreach ($errors as $e)
            {
                $const = $e->getConstraint();
                $groups = $const->groups;

                    $details[$groups[0]][] = $const->message;
                          
            }
        }
        return $details;
    }

    
    private function gestonarRequest(Request $request, $class, $classType, $id)
    {
        $em = $this->getDoctrine()->getManager();
        if ($id)
        {
            $entity = $em->find($class, $id);
        }
        else
        {
            $entity = new $class();
        }
        $form = $this->createForm($classType, $entity); //$this->getFormAltaMarcaChasis($entity);
        $form->handleRequest($request);
        $errors = $this->validateEntity($entity);
        if (count($errors))
        {
            return new JsonResponse(['ok' => false, 'errors' => $errors]);
        }    
        try
        {
            if (!$id)
            {
                $em->persist($entity);
            }
            $em->flush();
            return new JsonResponse(['ok' => true]);
        }
        catch (\Exception $e) { return new JsonResponse(['ok' => false, 'message' => $e->getMessage()]); }
    }

    ////////////////////GESTIONAR CATALOGOS////////////////////

    /**
     * @Route("/catalogs", name="seguridad_vial_gestion_catalogos")
     */
    public function gestionCatalogosVentas()
    {
        return $this->render('controller/gestion_documentos/catalogos.html.twig');
    }

    /////Organismos Estatales//////////////////

    /**
     * @Route("/catalogs/orgest", name="seguridad_vial_gestion_catalogos_organismos_estatatles")
     */
    public function gestionCatalogosOrganismosEstatales()
    {
        $em = $this->getDoctrine();

        $data = $em->getRepository(OrganismoEstatal::class)->findAll();

        $form = $this->createForm(OrganismoEmisorType::class, new OrganismoEstatal());

        return $this->render('controller/gestion_documentos/opciones/abmOrganismosEstatales.html.twig', ['form' => $form->createView() ,'organismos' => $data]);
    }

    /**
     * @Route("/catalogs/orgest/procesar/{id}", name="seguridad_vial_gestion_organismos_estatales_procesar")
     */
    public function gestionCatalogosOrganismosEstatalesProcesar($id = 0, Request $request)
    {
        return $this->gestonarRequest($request, OrganismoEstatal::class, OrganismoEmisorType::class, $id);
    }

    ///////////////

    /////Planta Verificacion//////////////////

    /**
     * @Route("/catalogs/plantav", name="seguridad_vial_gestion_catalogos_plantas_verificacion")
     */
    public function gestionCatalogosPlantasVerificacion()
    {
        $em = $this->getDoctrine();

        $data = $em->getRepository(PlantaVerificacion::class)->findAll();

        $form = $this->createForm(PlantaVerificacionType::class, new PlantaVerificacion());

        return $this->render('controller/gestion_documentos/opciones/abmPlantasVerificacion.html.twig', ['form' => $form->createView() ,'plantas' => $data]);
    }

    /**
     * @Route("/catalogs/plantav/procesar/{id}", name="seguridad_vial_gestion_plantas_verificacion_procesar")
     */
    public function gestionCatalogosPlantasVerificacionProcesar($id = 0, Request $request)
    {
        return $this->gestonarRequest($request, PlantaVerificacion::class, PlantaVerificacionType::class, $id);
    }

    ///////////////

    /////Compañias de Seguro//////////////////

    /**
     * @Route("/catalogs/cniaseg", name="seguridad_vial_gestion_catalogos_compania_seguro")
     */
    public function gestionCatalogosCompaniaSeguro()
    {
        $em = $this->getDoctrine();

        $data = $em->getRepository(CompaniaSeguro::class)->findAll();

        $form = $this->createForm(CompaniaSeguroType::class, new CompaniaSeguro());

        return $this->render('controller/gestion_documentos/opciones/abmCompaniaSeguro.html.twig', ['form' => $form->createView() ,'companias' => $data]);
    }

    /**
     * @Route("/catalogs/cniaseg/procesar/{id}", name="seguridad_vial_gestion_catalogos_compania_seguro_procesar")
     */
    public function gestionCatalogosCompaniaSeguroProcesar($id = 0, Request $request)
    {
        return $this->gestonarRequest($request, CompaniaSeguro::class, CompaniaSeguroType::class, $id);
    }

    ///////////////

    /////Tpo Destino Seguro//////////////////

    /**
     * @Route("/catalogs/tipodest", name="seguridad_vial_gestion_catalogos_tipo_destino_seguro")
     */
    public function gestionCatalogosTipoDestinoSeguro()
    {
        $em = $this->getDoctrine();

        $data = $em->getRepository(TipoDestinoSeguro::class)->findAll();

        $form = $this->createForm(TipoDestinoSeguroType::class, new TipoDestinoSeguro());

        return $this->render('controller/gestion_documentos/opciones/abmTipoDestinoSeguro.html.twig', ['form' => $form->createView() ,'tipos' => $data]);
    }

    /**
     * @Route("/catalogs/tipodest/procesar/{id}", name="seguridad_vial_gestion_catalogos_tipo_destino_seguro_procesar")
     */
    public function gestionCatalogosTipoDestinoSeguroProcesar($id = 0, Request $request)
    {
        return $this->gestonarRequest($request, TipoDestinoSeguro::class, TipoDestinoSeguroType::class, $id);
    }

    ///////////////

    /////Tpo Cobertura Seguro//////////////////

    /**
     * @Route("/catalogs/cobertura", name="seguridad_vial_gestion_catalogos_cobertura_seguro")
     */
    public function gestionCatalogosCoberturaSeguro()
    {
        $em = $this->getDoctrine();

        $data = $em->getRepository(CoberturaSeguro::class)->findAll();

        $form = $this->createForm(CoberturaSeguroType::class, new CoberturaSeguro());

        return $this->render('controller/gestion_documentos/opciones/abmCoberturaSeguro.html.twig', ['form' => $form->createView() ,'coberturas' => $data]);
    }

    /**
     * @Route("/catalogs/cobertura/procesar/{id}", name="seguridad_vial_gestion_catalogos_cobertura_seguro_procesar")
     */
    public function gestionCatalogosCoberturaSeguroProcesar($id = 0, Request $request)
    {
        return $this->gestonarRequest($request, CoberturaSeguro::class, CoberturaSeguroType::class, $id);
    }

    ///////////////

    ////////////////////FIN GESTIONAR CATALOGOS///////////////////////////////



    /**
     * @Route("/pagos/cuota/registrar/{id}", name="controller_gestion_documentos_pagos_registrar_cuuota")
     */
    public function registrarCuotaPagoVencimiento($id, Request $request): Response
    {
        try
        {
            $em = $this->getDoctrine()->getManager();

templates/controller/gestion_documentos/habilitaciones/index.html.twig
{% extends 'sistema/base.html.twig' %}
{% set datatable = true %}
{% block stylesheets %}

<link rel="stylesheet" href="{{ asset('resources/css/style.css') }}" rel="stylesheet">

{% endblock %}

{% block title_module %}
    Habilitaciones Vigentes
{% endblock %}

{% block content %}
        <div class="card">
            <div class="row pt-2 pb-2">
                
                            <div class="col-lg-6">
                                <div class="row">
                                        <div class="col-lg-1 align-middle mt-2 ml-2">
                                                <a class='btn-filter'><i class="fas fa-filter"></i></a>
                                        </div>
                                        <div class="col-lg-6 align-middle mt-2">
                                                
                                        </div>
                                </div>
                            </div>
                            <div class="col d-flex align-items-end">

                                <!-- Basic dropdown -->
                                <button class="btn btn-success dropdown-toggle btn-sm" type="button" data-toggle="dropdown"
                                  aria-haspopup="true" aria-expanded="false">Agregar</button>

                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{{ path('controller_gestion_documentos_nueva_habilitaciones', { type : 9}) }}">Turismo Nacional</a>
                                  <a class="dropdown-item" href="{{ path('controller_gestion_documentos_nueva_habilitaciones', { type : 11}) }}">Oferta Libre (Charter)</a>
                                  <a class="dropdown-item" href="{{ path('controller_gestion_documentos_nueva_habilitaciones', { type : 12}) }}">Oferta Libre (Contratado)</a>
                                  <a class="dropdown-item" href="{{ path('controller_gestion_documentos_nueva_habilitaciones', { type : 14}) }}">Turismo Provincial</a>
                                </div>
                                <!-- Basic dropdown -->
                                
                                <a class="btn btn-sm round btn-danger align-middle"><i class="fas fa-trash-alt mr-1"></i>Elimnar</a>
                                <a class="btn btn-sm btn-blue-grey">Opciones</a>
                            </div>
                

            </div>
        </div>
        <div class="card mt-1">
                <div class="mb-2">
                        <div class="message">
                                {% include 'gestion/messages.html.twig'  %}
                        </div>
                </div>
        <table id="dt-filter-select" class="table table-sm table-hover table-striped table-bordered ml-1 mr-1" cellspacing="0" width="100%">

          <thead>
                    <tr class="filters" style="display: none;">
                        <th colspan="2" class="p-2 align-middle">Filtrar</th>
                        <th class="p-2"><input type="text" class="form-control form-control-sm p-2" placeholder="Razon Social"></th>
                        <th class="p-2"><input type="text" class="form-control form-control-sm p-2" placeholder="Nombre Fantasia"></th>
                        <th class="p-2"><input type="text" class="form-control form-control-sm p-2" placeholder="Estado"></th>
                    </tr>
            <tr>
              <th scope="col"></th>
              <th scope="col">Tipo</th>
              <th scope="col">Certificado</th>
              <th scope="col">Emision</th>
              <th scope="col">Organismo Emisor</th>
              <th scope="col">Vigencia Hasta</th>
              <th scope="col">Unidad</th>
            </tr>
          </thead>
          <tbody>
            {% for d in detalle %}
                <tr>
                    <td>
                        <a href="{{ path('controller_gestion_documentos_nueva_habilitaciones', { type: d.type, id : d.id }) }}"><i class="fas fa-pencil-alt"></i></a>
                    </td>
                    <td> {{ d.texto }} </td>
                    <td>{{ d.codigoHabilitacion }}</td>
                    <td>{{ d.emision|date('d/m/Y') }}</td>            
                    <td>{{ d.proveedor|upper }}</td>
                    <td>{{ d.vigenciaDesde|date('d/m/Y') }} - {{ d.vigenciaHasta|date('d/m/Y') }}</td>
                    <td>{{ d.unidades|length }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}

{% block javascripts %}

<script type="text/javascript">
        
        $(document).ready(function(){   

                setTimeout(function(){
                    $('.message').hide();
                }, 4000);

                $('#dt-filter-select tbody').on( 'click', 'tr', function () {
                    if ( $(this).hasClass('selected') ) {
                        $(this).removeClass('selected');
                    }
                    else {
                        $('#dt-filter-select tr.selected').removeClass('selected');
                        $(this).addClass('selected');
                    }
                } );

                const route_edit = "{{ path('editar_cliente', { id : 'CLIENTE_ID'}) }}";

                $('.btn-edit').click(function(event){
                                                        event.preventDefault();
                                                        var chk = $("input[name='clientes']:checked").data('cliente');
                                                        if (chk)
                                                        {
                                                            window.location.href = route_edit.replace('CLIENTE_ID', chk);
                                                        }
                                                        else
                                                        {
                                                            bootbox.message('dsadsadasd');
                                                        }
                });

                $('.btn-filter').click(function(){
                                                    $('.filters').toggle(50,function() {

                                                    });
                });


                $('#dt-filter-select thead tr:eq(0) th').each( function (i) {
                    var title = $(this).text();

                    $( 'input', this ).on( 'keyup change', function () {
                        if ( table.api().column((i+1)).search() !== this.value ) {
                            table
                                .api()
                                .column((i+1))
                                .search( this.value )
                                .draw();
                        }
                    } );
                } );

                const route = "{{ path('cliente_change_state', { id : 'CLIENTE_ID'}) }}";

                 var table = $('#dt-filter-select').dataTable({                                                                                  
                                                                "paging": true,
                                                                "info" : false,
                                                                "searching": false,
                                                                "lengthChange": false,
                                                                "bFilter" : true,
                                                                "language": {
                                                                            "paginate": {
                                                                                          "first": "Primera",
                                                                                          "last": "Ultima",
                                                                                          "previous" : "Anterior",
                                                                                          "next" : "Siguiente"
                                                                                        }
                                                                            }
                });

                $('.state').change(function(){
                                               const btn = $(this);
                                               const id = btn.data('id');
                                               let idroute = route.replace('CLIENTE_ID', id);
                                               const state = (btn.is(':checked') == true)?1:0;
                                               $.post(idroute,
                                                      {'state' : state},
                                                      function(data){
                                                            if(data.status)
                                                            {
                                                                if (state)
                                                                {
                                                                    $('#span'+id).html('Activo');
                                                                }
                                                                else
                                                                {
                                                                    $('#span'+id).html('Inactivo');
                                                                }
                                                            }
                                                            else
                                                            {
                                                                alert(data.message);
                                                            }
                                                      });
                                               
                });
        });

</script>
{% endblock %}